apiVersion: 1

datasources:
  - name: PostgreSQL-Czech
    type: postgres
    access: proxy
    url: postgres:5432
    database: landomo_czech
    user: landomo
    secureJsonData:
      password: aNDppWQUiO60ODBZKe6ODCDPxtfsqTYh
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true

  - name: PostgreSQL-Germany
    type: postgres
    access: proxy
    url: postgres:5432
    database: landomo_germany
    user: landomo
    secureJsonData:
      password: aNDppWQUiO60ODBZKe6ODCDPxtfsqTYh
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    editable: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    jsonData:
      client: standalone
    editable: true
