/**
 * Property Type Definitions
 *
 * Matches backend schema (search-service/src/types/search.ts)
 * NO backward compatibility - clean break from old mock schema.
 */

import { PropertyResult } from '@/lib/api/types';

// ============================================================================
// Core Property Types
// ============================================================================

export interface PropertyCoordinates {
  lat: number;
  lng: number;
}

export interface PropertyFeature {
  id: string;
  name: string;
  icon: string; // Lucide icon name
}

export interface PriceHistoryEntry {
  date: string; // ISO date string (YYYY-MM-DD)
  price: number;
}

/**
 * Property interface - extends backend PropertyResult with computed fields
 */
export interface Property extends PropertyResult {
  // Computed fields (generated by adaptProperty)
  coordinates?: PropertyCoordinates;
  features?: PropertyFeature[];
  pricePerSqm?: number;
  priceHistory?: PriceHistoryEntry[];

  // Agent info (structured from flat fields)
  agent?: {
    name: string;
    phone: string;
    email: string;
    photo?: string;
  };
}

// ============================================================================
// Filter Types
// ============================================================================

export interface PropertyFilter {
  // Price
  price_min?: number;
  price_max?: number;

  // Category & Type
  property_category?: 'apartment' | 'house' | 'land' | 'commercial';
  property_type?: string;
  transaction_type?: 'sale' | 'rent' | 'auction';

  // Location
  city?: string;
  region?: string;
  country?: string;

  // Size
  sqm_min?: number;
  sqm_max?: number;
  bedrooms_min?: number;
  bedrooms_max?: number;
  bathrooms_min?: number;

  // Amenities
  has_parking?: boolean;
  has_balcony?: boolean;
  has_elevator?: boolean;
  has_garden?: boolean;
  has_garage?: boolean;
  has_pool?: boolean;
  has_terrace?: boolean;
  has_basement?: boolean;

  // Czech-specific
  disposition?: string;
  ownership?: string;
  building_type?: string;
  condition?: string;

  // UK-specific
  tenure?: string;
  epc_rating?: string | string[];

  // Full-text
  search_query?: string;
}

// ============================================================================
// Alert Types
// ============================================================================

export interface PropertyAlert {
  id: string;
  type: 'price_drop' | 'new_listing' | 'property_update' | 'location_based';

  // Property-specific alerts
  propertyId?: string;
  priceThreshold?: number;

  // Search-based alerts
  searchCriteria?: PropertyFilter;
  locationRadius?: number; // in meters
  centerCoordinates?: PropertyCoordinates;

  // Delivery preferences
  frequency: 'instant' | 'daily' | 'weekly';
  channels: ('in_app' | 'email' | 'push')[];

  // Status
  active: boolean;
  muted: boolean;
  createdAt: string;
  lastTriggered?: string;

  // Metadata
  triggerCount: number;
  maxNotificationsPerDay?: number;
}

export interface NotificationHistoryItem {
  id: string;
  alertId: string;
  type: 'new_property' | 'price_change' | 'saved_search' | 'favorite' | 'property_update';
  title: string;
  message: string;
  timestamp: string;
  unread: boolean;

  // Related data
  propertyId?: string;
  metadata?: {
    oldPrice?: number;
    newPrice?: number;
    changeAmount?: number;
    changePercent?: number;
  };
}

// ============================================================================
// Adapter Functions: Backend PropertyResult → Frontend Property
// ============================================================================

/**
 * Converts backend PropertyResult to frontend Property with computed fields
 */
export function adaptProperty(result: PropertyResult): Property {
  // Calculate price per sqm (skip for "na dotaz" listings)
  const pricePerSqm = result.price > 1 && result.sqm && result.sqm > 0
    ? Math.round(result.price / result.sqm)
    : undefined;

  // Parse string lat/lon to numbers (PostgreSQL NUMERIC returns strings)
  const lat = typeof result.latitude === 'string' ? parseFloat(result.latitude) : result.latitude;
  const lon = typeof result.longitude === 'string' ? parseFloat(result.longitude) : result.longitude;

  // Build coordinates
  const coordinates: PropertyCoordinates | undefined =
    lat !== undefined && lon !== undefined && !isNaN(lat) && !isNaN(lon)
      ? { lat, lng: lon }
      : undefined;

  // Build features from amenities
  const features: PropertyFeature[] = [];
  if (result.has_parking) features.push({ id: 'parking', name: 'Parking', icon: 'parking-circle' });
  if (result.has_balcony) features.push({ id: 'balcony', name: 'Balcony', icon: 'snowflake' });
  if (result.has_terrace) features.push({ id: 'terrace', name: 'Terrace', icon: 'sun' });
  if (result.has_garden) features.push({ id: 'garden', name: 'Garden', icon: 'tree-deciduous' });
  if (result.has_elevator) features.push({ id: 'elevator', name: 'Elevator', icon: 'move-vertical' });
  if (result.has_garage) features.push({ id: 'garage', name: 'Garage', icon: 'warehouse' });
  if (result.has_pool) features.push({ id: 'pool', name: 'Pool', icon: 'waves' });
  if (result.has_basement) features.push({ id: 'basement', name: 'Basement', icon: 'box' });

  // Build agent object (show when any contact info exists)
  const agent = (result.agent_name || result.agent_phone || result.agent_email) ? {
    name: result.agent_name || '',
    phone: result.agent_phone || '',
    email: result.agent_email || '',
  } : undefined;

  // Sanitize image URLs — encode pipe characters that cause 400 errors on sdn.cz
  // Filter out Matterport URLs (3D tour links, not actual images)
  const images = result.images
    ?.filter(url => !url.includes('matterport.com'))
    .map(url => url.replace(/\|/g, '%7C'));

  // Normalize "m2" → "m²" in titles
  const title = result.title?.replace(/(\d)\s*m2\b/g, '$1 m²');

  // Normalize currency variants to standard code
  const currency = result.currency === 'Kc/mes.' ? 'CZK' : result.currency;

  return {
    ...result,
    title,
    images,
    currency,
    latitude: lat,
    longitude: lon,
    // Computed fields
    pricePerSqm,
    coordinates,
    features,
    agent,
  };
}

/**
 * Batch adapter for multiple properties
 */
export function adaptProperties(results: PropertyResult[]): Property[] {
  return results.map(adaptProperty);
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Get display address from property (uses title field)
 * For Czech properties, title usually contains disposition and area
 * Example: "Prodej bytu 3+kk 78 m²"
 */
export function getPropertyAddress(property: Property): string {
  return property.title || property.city;
}

/**
 * Extract short address without disposition/area (Czech-specific)
 * "Prodej bytu 3+kk 78 m², Praha 2" → "Praha 2"
 */
export function getShortAddress(property: Property): string {
  // For Czech properties, city is usually cleaner than title
  return property.city || property.title;
}

/**
 * Get floor display (e.g., "3rd floor", "Ground floor")
 */
export function getFloorDisplay(floor?: number): string | undefined {
  if (floor === undefined) return undefined;
  if (floor === 0) return 'Ground';
  if (floor === 1) return '1st';
  if (floor === 2) return '2nd';
  if (floor === 3) return '3rd';
  return `${floor}th`;
}

/**
 * Format price with currency symbol
 */
export function isPriceOnRequest(price: number): boolean {
  return price <= 1;
}

export function formatPrice(price: number, currency: string = 'CZK'): string {
  if (isPriceOnRequest(price)) return 'na dotaz';

  if (currency === 'CZK') {
    return `${price.toLocaleString("cs-CZ")} Kč`;
  }
  const currencySymbol = currency === 'EUR' ? '€'
    : currency === 'USD' ? '$'
    : currency === 'GBP' ? '£'
    : currency;

  return `${currencySymbol}${price.toLocaleString()}`;
}

/**
 * Format area in square meters
 */
export function formatArea(sqm?: number): string {
  return sqm ? `${sqm} m²` : '';
}

/**
 * Get property category display name
 */
export function getCategoryDisplayName(category: string): string {
  const map: Record<string, string> = {
    apartment: 'Apartment',
    house: 'House',
    land: 'Land',
    commercial: 'Commercial',
  };
  return map[category] || category;
}

/**
 * Get transaction type display name
 */
export function getTransactionDisplayName(type: string): string {
  const map: Record<string, string> = {
    sale: 'For Sale',
    rent: 'For Rent',
  };
  return map[type] || type;
}

/**
 * Get disposition display (Czech properties)
 */
export function getDisposition(property: Property): string | undefined {
  return property.czech_disposition || property.disposition_description;
}

/**
 * Get ownership display (Czech properties)
 */
export function getOwnershipDisplay(ownership?: string): string | undefined {
  if (!ownership) return undefined;

  const map: Record<string, string> = {
    personal: 'Personal',
    private: 'Private',
    cooperative: 'Cooperative',
    collective: 'Collective',
    state: 'State',
    other: 'Other',
  };
  return map[ownership] || ownership;
}

/**
 * Get construction type display (Czech properties)
 */
export function getConstructionTypeDisplay(type?: string): string | undefined {
  if (!type) return undefined;

  const map: Record<string, string> = {
    brick: 'Brick',
    panel: 'Panel',
    stone: 'Stone',
    wood: 'Wooden',
    mixed: 'Mixed',
    concrete: 'Concrete',
    prefab: 'Prefab',
    steel: 'Steel',
    other: 'Other',
  };
  return map[type] || type;
}

/**
 * Get condition display
 */
export function getConditionDisplay(condition?: string): string | undefined {
  if (!condition) return undefined;

  const map: Record<string, string> = {
    new: 'New',
    excellent: 'Excellent',
    very_good: 'Very Good',
    good: 'Good',
    after_reconstruction: 'After Reconstruction',
    after_renovation: 'After Renovation',
    requires_renovation: 'Requires Renovation',
    original_state: 'Original State',
    under_construction: 'Under Construction',
    project: 'Project',
  };
  return map[condition] || condition;
}

/**
 * Get heating type display
 */
export function getHeatingTypeDisplay(type?: string): string | undefined {
  if (!type) return undefined;

  const map: Record<string, string> = {
    central: 'Central',
    local: 'Local',
    gas: 'Gas',
    electric: 'Electric',
    solid_fuel: 'Solid Fuel',
    heat_pump: 'Heat Pump',
    floor: 'Floor Heating',
    other: 'Other',
  };
  return map[type] || type;
}

/**
 * Get furnished status display
 */
export function getFurnishedDisplay(furnished?: string | boolean): string | undefined {
  if (furnished === undefined || furnished === null) return undefined;

  if (typeof furnished === 'boolean') {
    return furnished ? 'Furnished' : 'Unfurnished';
  }

  const map: Record<string, string> = {
    furnished: 'Furnished',
    partially_furnished: 'Partially Furnished',
    unfurnished: 'Unfurnished',
    not_furnished: 'Unfurnished',
  };
  return map[furnished] || furnished;
}

/**
 * Get floor location display (Czech properties)
 */
export function getFloorLocationDisplay(location?: string): string | undefined {
  if (!location) return undefined;

  const map: Record<string, string> = {
    ground: 'Ground Floor',
    middle: 'Middle Floors',
    top: 'Top Floor',
  };
  return map[location] || location;
}

/**
 * Format bedrooms from disposition (Czech)
 * Examples: "3+kk" → 3 bedrooms, "2+1" → 2 bedrooms
 */
export function getBedroomsFromDisposition(disposition?: string): number | undefined {
  if (!disposition) return undefined;

  const match = disposition.match(/^(\d+)/);
  return match ? parseInt(match[1], 10) : undefined;
}
